### ISSUE TITLE
General questions about react-transmit usage within this kit

### ISSUE THREAD

**Issue by kulikalov** [RickWong/react-isomorphic-starterkit#134]
Hi

First of all, thanks a lot for this kit :)

I was using it with flux and redux already and now i'm looking at `react-transmit`.

I've never used Relay with GraphQL or react-transmit before, so i'm a bit confused about some very basic concepts. Based on Relay docs and tutorials i'm assuming, that this is the replacement to flux/redux. And react-transmit is the alternative to Relay. However, i guess, i have a misconception of some basic idea behind this and therefore have all this lame questions.

1. The entire dataflow for a Component happening basically in the same place? No client-side stores, reducers and other stuff?
2. If so, then how do i handle data sharing between different components? Let's say i'm building a blog. A user is authenticated, so, sidebar has information about user's session, but also, "Comments" component suppose to have it. Do i suppose to make a request to server to get this data on each render of "Comments" components? Or may be i should use flux/redux exclusively for client-side dataflow so the session data will be stored in there? Or pass the data as props/context to all of the descendants? What is the conventional way to handle this?
3. What about posting data? It seems possible to do it with the same code, but functions named like "fetch..." tell me that this code suppose to fetch, not post. So, in this case i should use direct requests to server the way i'd like (REST or web-socket)?

**Comment by kulikalov** [comment]
May be there are some articles/videos/docs that i should read to understand that?

**Comment by RickWong** [comment]
Hi! You got it all right. 

1. Transmit does not necessarily handle the entire data flow. It simply colocates the queries within your smart components. That basically means that the required props of a component are declared in the same file in order to prevent over- or under-fetching. The smart components are directly responsible for getting rendered correctly themselves.
2. Transmit uses Promises to resolve props. It's up to you to decide what the Promises do. Whether they perform API requests directly or depend on a centralized store, or a bit of both, as long as they resolve the required props, then they're valid Transmit queries.
3. Querying and resolving are Transmit's strengths. I'll have to admit that mutations aren't well supported. I dislike Relay's mutation interface because it's really complex. But I haven't had a good idea about how to implement them in Transmit. I suppose next to the `queries` option there should be a `mutations` option with functions and those should be made available by Transmit to the wrapped component. Like I said, this is not yet implemented. Currently my advice is to keep it simple and outside of Transmit. 

Please do take a look at [React Resolver](https://github.com/ericclemmons/react-resolver) by @ericclemmons as well. Perhaps that project suits your project better.
