### ISSUE TITLE
`Server-side React render was discarded` after migrating to express

### ISSUE THREAD

**Issue by kulikalov** [RickWong/react-isomorphic-starterkit#135]
Is there any critical dependency on koa? I've replaced it with express, everything seems to work absolutely ok, but i'm getting this warning in browser's console:

```
Server-side React render was discarded. Make sure that your initial render does not contain any client-side code.
```

btw, did you think about migrating to express? It's not a big difference and mostly just a matter of taste, but if you want i can do it and create a PR

**Comment by RickWong** [comment]
There is no critical dependency on Koa. It's just that Koa is more modular than Express, so I prefer the former.

The error is caused by an inconsistent first client render of the DOM, that differs from the DOM that the server sent down. React can therefore not quickboot. 

Check whether the client-rendered DOM (Elements in Devtools) matches the server sent DOM (View Source). Also check whether the server sent down any required Transmit variables!
