### ISSUE TITLE
(Transmit) Caching query results

### ISSUE THREAD

**Issue by dennis-van-bennekom** [RickWong/react-isomorphic-starterkit#30]
Hey again,

When I reload a page with a component that does a query it does the query again every time. Is there an option or way to cache the query results?

Thanks,
Dennis

**Comment by RickWong** [comment]
Yes, you can use the React Transmit's `onQuery` handler to cache query results. https://github.com/RickWong/react-transmit/blob/master/DOCS.md#onquerypromise--function

**Comment by dennis-van-bennekom** [comment]
Thanks!

I am figuring out how to get the caching working:

``` javascript
onQuery: (promise) => {
    if (this.props.tweets) {
      promise.resolve(this.props.tweets);
    }
},
```

I was something like this, but that doesn't do anything. Any hints or tips on how to approach this problem?

**Comment by RickWong** [comment]
Try something like this:

``` js
Parent {
  getInitialState () { 
    return {};
  }

  onQuery(promise) {
    promise.then((results) => {
      this.setState(results);  // this will cache the 'foobar' query result
    });
  }

  render () {
    return <Child onQuery={this.onQuery} foobar={this.state.foobar} />;
  }
}
```

``` js
Child {
  render () {
    return <div>{this.props.foobar}</div>;
  }
}

export default Transmit.createContainer(Child, {
  queries: {
    foobar () {
      return fetch(...);
    }
  }
});
```

**Comment by dennis-van-bennekom** [comment]
Thanks for the example!

``` javascript
onQuery (promise) {
    promise.then((results) => {
      this.setState(results);
    });
  }
```

^ this only returns an empty object for me, the results object `=== {}`. When I leave the onQuery part out it works, except I don't get caching ofcourse :disappointed_relieved:.

**Comment by RickWong** [comment]
The `promise` given to `onQuery` allows you to cache the results. There's no need to call `setState` because that is handled by Transmit automatically. Unless you want to the parent's `state` as a cache, which you probably don't because the parent is probably also wiped in-between route changes... The best solution is to store the results somewhere outside of the React tree, like in a Flux store for example. Then pass the cached results to the child as props.

Maybe I'll change the example to include multiple routes, then it can also showcase how to cache.
