### ISSUE TITLE
Flux?

### ISSUE THREAD

**Issue by goatslacker** [RickWong/react-isomorphic-starterkit#4]
This starter kit should probably have an opinion on how data is fetched and stored. Flux is a great pattern to adopt.

**Comment by RickWong** [comment]
Thanks for the suggestion man :+1:  However there are too many Flux implementations out there, without 1 clear winner. I do not think it's fair to include one implementation for the sake of including one. Maybe in a few months there'll be a Flux/Relay implementation that stands out. (I do hope so)

For now this starterkit's focus is making the isomorphic workflow & build system as pleasant as possible.

**Comment by appsforartists** [comment]
An isomorphic app isn't useful if the data model isn't isomorphic too.

There are indeed many viable contenders, but you might want to just pick one and go for it (like you did with Hapi).

**Comment by RickWong** [comment]
Right now the `ContextHelper.Mixin` allows you to load data to render on the server and then automatically pass that data to the client, so the client gets hydrated with the same data. I believe this isomorphic "bridging" functionality is enough to make simple apps work. Even bigger apps can benefit from it in exactly the same way. For example, after you've Fluxed some data on the server, use the ContextHelper to pass it to the client. There, once hydrated, Flux on.

Hope that made sense!

**Comment by appsforartists** [comment]
Interesting.

Have you run that by anyone from React?  I think that's overloading what context is designed for.  The only uses I've seen of context are to pass environment-wise variables down the tree to components that might need them.  I expect manually mutating `this.context` from a mixin runs contrary to its intended design, which could end up confusing users or breaking the expected behavior.

I could be completely mistaken, but if I'm not, you may want to consider renaming your magic property to something that React hasn't already defined.

**Comment by RickWong** [comment]
I know it might feel weird at first. But do take some time to think about how context should continue and not end on the server. In this starterkit context is considered "isomorphic" as well. Because in an isomorphic app the components are the same components on the server as they are on the client ("isomorphic components"). The visitor's request is processed both on the server and on client: it's the SAME request – even though both the server and client work together to generate the response. It actually makes sense to share the same context ("isomorphic context"). Because otherwise how will the client know what happened on the server? How will it continue the same request? If it needs to AJAX-load the data again, then it's not isomorphic anymore.

About context mutation: the reason that `this.context` is mutated is because there's no mounting nor `this.setState()` on the server. React does NOT provide the lovely component lifecycle that is available on the client. But by using a mutable context, and going through the components twice with `React.renderToString()`, this starterkit breathes a synthetic serverside lifecycle into the components. Making the components powerful enough and capable to load their own data. 

Checkout `Main.jsx` to see how the above results into an isomorphic app that: does not pollute node's global state simply by using a unique context per request, and: lets the components decide what data they need to load, and: has the same data present on the server and on the client.

With this starterkit, React components on the server aren't just a template engine anymore.

**Comment by appsforartists** [comment]
My issue was more with the name - `context` is defined to have a particular API (`getChildContext`, `childContextTypes`, and `contextTypes`) and it automatically passes itself on to all the descendent components.

It sounds like you want a bag of data to pass between the server and client (because, as you've said, they are both working together to serve the same user).  What if your new concept was called `isomorphicData` instead of `context`?  Then, it would be clear to someone reading starterkit-inspired code that you're leveraging your own concept that won't be confused with one that's already well-defined to many React developers.

**Comment by RickWong** [comment]
That's worth thinking about. Naming is really hard. The word "isomorphic" has a different meaning in everyone's mind. At any rate thanks for the feedback :+1: Really delicious food for thought.
